server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.26.34:3306/movie?characterEncoding=utf8&serverTimezone=UTC
    username: movie
    password: 3CGTMaeXrCdB5rBn
  cache:
    redis:
      #使用前
      use-key-prefix: true
      time-to-live: 60s
mybatis-plus:
  global-config:
    db-config:
      id-type: uuid
  type-aliases-package: com.movie.api.model.entity